default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gocase_ch_development

test:
  <<: *default
  database: gocase_ch_test

production:
  <<: *default
  database: gocase_ch_production
  username: gocase_ch
  password: <%= ENV['GOCASE_CH_DATABASE_PASSWORD'] %>
